astropy/sphinx-automodapi

- sphinx_automodapi/automodapi.py
- sphinx_automodapi/tests/test_automodapi.py
Same as https://github.com/astropy/astropy-helpers/pull/244
Should I close the PR on astropy-helpers ? What's the next step for sphinx-automodapi, do you plan to do a release and use it directly in astropy-helpers and astropy ?
> Fix encoding error with automodapi_writereprocessed and py2

- CHANGES.rst
- sphinx_automodapi/automodapi.py
- sphinx_automodapi/automodsumm.py
This came up while trying to bundle sphinx_automodapi in astropy-helpers
> Avoid hard-coding sphinx_automodapi module name

- CHANGES.rst
- sphinx_automodapi/automodapi.py
- sphinx_automodapi/automodsumm.py
- sphinx_automodapi/tests/cases/mixed_toplevel_all_objects/README.md
- sphinx_automodapi/tests/cases/mixed_toplevel_all_objects/input/index.rst
- sphinx_automodapi/tests/cases/mixed_toplevel_all_objects/output/api/sphinx_automodapi.tests.example_module.Egg.rst
- sphinx_automodapi/tests/cases/mixed_toplevel_all_objects/output/api/sphinx_automodapi.tests.example_module.FUNNY_WALK_STEPS.rst
- sphinx_automodapi/tests/cases/mixed_toplevel_all_objects/output/api/sphinx_automodapi.tests.example_module.PARROT_STATE.rst
- sphinx_automodapi/tests/cases/mixed_toplevel_all_objects/output/api/sphinx_automodapi.tests.example_module.Spam.rst
- sphinx_automodapi/tests/cases/mixed_toplevel_all_objects/output/api/sphinx_automodapi.tests.example_module.add.rst
- sphinx_automodapi/tests/cases/mixed_toplevel_all_objects/output/api/sphinx_automodapi.tests.example_module.multiply.rst
- sphinx_automodapi/tests/cases/mixed_toplevel_all_objects/output/index.rst.automodapi
- sphinx_automodapi/tests/cases/mixed_toplevel_all_objects/output/index.rst.automodsumm
- sphinx_automodapi/tests/cases/variables/README.md
- sphinx_automodapi/tests/cases/variables/input/index.rst
- sphinx_automodapi/tests/cases/variables/output/api/sphinx_automodapi.tests.example_module.variables.FUNNY_WALK_STEPS.rst
- sphinx_automodapi/tests/cases/variables/output/api/sphinx_automodapi.tests.example_module.variables.PARROT_STATE.rst
- sphinx_automodapi/tests/cases/variables/output/index.rst.automodapi
- sphinx_automodapi/tests/cases/variables/output/index.rst.automodsumm
- sphinx_automodapi/tests/example_module/__init__.py
- sphinx_automodapi/tests/example_module/variables.py
- sphinx_automodapi/tests/test_cases.py
This is a rebase with renamed arguments of https://github.com/astropy/astropy-helpers/pull/198, since the automodapi routines now seem to live here.
> Allow also non-functions/classes to be included in module API summary.

- CHANGES.rst
- sphinx_automodapi/automodsumm.py
- sphinx_automodapi/tests/cases/abstract_classes/README.md
- sphinx_automodapi/tests/cases/abstract_classes/input/index.rst
- sphinx_automodapi/tests/cases/abstract_classes/output/api/sphinx_automodapi.tests.example_module.abstract_classes.SequenceSubclass.rst
- sphinx_automodapi/tests/cases/abstract_classes/output/index.rst.automodapi
- sphinx_automodapi/tests/cases/abstract_classes/output/index.rst.automodsumm
- sphinx_automodapi/tests/example_module/abstract_classes.py
- sphinx_automodapi/tests/test_cases.py
ABC-derived classes (i.e. those deriving from the `abc` and `collections.abc` modules) now include their members (as defined in `__dict__`) in generated `autosummary` RST. `__slots__` may still be used to override `__dict__`, but if an ABC-derived class has empty slots, its `__dict__` will be used instead.
This was only an issue in Python 3 when ``:inherited-members:`` was not in effect.
Fixes #52
> Fix issue with ABC-derived classes having their members ignored in Python 3

- setup.cfg
- setup.py
Looks like everything can be done through setup.cfg here! As for astropy core, this means that setuptools 30 or later is required (although most users will probably install from wheels so it probably won't matter). Should we include a version check for setuptools in setup.py?
> Moved setup configuration to setup.cfg

- CHANGES.rst
- sphinx_automodapi/automodapi.py
- sphinx_automodapi/tests/test_automodapi.py
I'm tired of having to constantly add ``:no-inheritance-diagram:`` in API docs so finally here is a global option, as discussed in https://github.com/astropy/sphinx-automodapi/issues/6.
For now let's leave the default as-is, and we can decide later whether to change it.
cc @cdeil
> Global configuration option for inheritance diagrams

- CHANGES.rst
- sphinx_automodapi/smart_resolver.py
Ran into this with the ipywidgets intersphinx inventory
> Fix smart resolver when intersphinx inventory doesn't include py:class

- CHANGES.rst
- sphinx_automodapi/autodoc_enhancements.py
- sphinx_automodapi/automodapi.py
- sphinx_automodapi/automodsumm.py
- sphinx_automodapi/tests/__init__.py
- sphinx_automodapi/tests/cases/func_headings/output/index.rst.automodsumm
- sphinx_automodapi/tests/cases/func_noheading/output/index.rst.automodsumm
- sphinx_automodapi/tests/cases/func_nomaindocstring/output/index.rst.automodsumm
- sphinx_automodapi/tests/cases/func_simple/output/index.rst.automodsumm
- sphinx_automodapi/tests/cases/mixed_toplevel/output/index.rst.automodsumm
- sphinx_automodapi/tests/cases/mixed_toplevel_all_objects/output/index.rst.automodsumm
- sphinx_automodapi/tests/cases/mixed_toplevel_nodiagram/output/index.rst.automodsumm
- sphinx_automodapi/tests/cases/non_ascii/output/index.rst.automodsumm
- sphinx_automodapi/tests/cases/source_dir/output/src/index.rst.automodsumm
- sphinx_automodapi/tests/example_module/__init__.py
- sphinx_automodapi/tests/example_module/functions.py
- sphinx_automodapi/tests/example_module/mixed.py
- sphinx_automodapi/tests/helpers.py
- sphinx_automodapi/tests/test_autodoc_enhancements.py
- sphinx_automodapi/tests/test_automodapi.py
- sphinx_automodapi/tests/test_automodsumm.py
- sphinx_automodapi/tests/test_cases.py
- sphinx_automodapi/utils.py
The issue in https://github.com/astropy/sphinx-automodapi/issues/80 was not caught previously because the way we ran some of the tests was to create a fake application class, which still had warn and info. Rather than try to adjust this to the latest Sphinx API, I changed these tests to properly use sphinx rather than 'fake' classes which will be more future proof.
Fixes https://github.com/astropy/sphinx-automodapi/issues/80
> Fix remaining instances of app.warn

- CHANGES.rst
- docs/index.rst
- setup.cfg
- sphinx_automodapi/autodoc_enhancements.py
- sphinx_automodapi/automodapi.py
- sphinx_automodapi/automodsumm.py
- sphinx_automodapi/tests/helpers.py
- sphinx_automodapi/tests/test_cases.py
- sphinx_automodapi/utils.py
- tox.ini
This closes #85 by updating the sphinx dependecy to 1.7 as discussed further in that issue.
One thing I realized I wasn't sure about: when I dropped all the older tox environments, there was nothing left for py2.7, so I added one back in that does py2.7 and sphinx 1.7, which seems sensible.  But I'm not 100% sure that one will work, so @astrofrog you might want to check that.
> Update sphinx req to 1.7 and add version "policy"

- azure-template.yml
- setup.cfg
- sphinx_automodapi/automodapi.py
- sphinx_automodapi/smart_resolver.py
When Spinx updated to `v3.0.0`, `sphinx-automodapi` started raising `KeyErrors` on `'refexplicit'` and `'refdoc'` in the `smart_resolver.missing_reference_handler()` function.  I could not find the change in Sphinx that caused this, but the update caused the original `node` to not be populated with these attributes anymore.  To resolve this I replaced the key call `node['refexplicit']` with a get call `node.get('refexplicit')`, which applies a default value if the key does not exist.
Based on this very helpful comment https://github.com/sphinx-doc/sphinx/issues/1572#issuecomment-68590981, I added docstrings and comments to better inform what the function does.
**Note:** I noticed these lines of code were not hit by tests, thus, the tests never failed.  I do not know enough about the …
> Fix keyerror on refexplicit and refdoc

- CHANGES.rst
- sphinx_automodapi/automodapi.py
- sphinx_automodapi/tests/cases/allowed_names/README.md
- sphinx_automodapi/tests/cases/allowed_names/input/index.rst
- sphinx_automodapi/tests/cases/allowed_names/output/api/sphinx_automodapi.tests.example_module.Egg.rst
- sphinx_automodapi/tests/cases/allowed_names/output/api/sphinx_automodapi.tests.example_module.Spam.rst
- sphinx_automodapi/tests/cases/allowed_names/output/index.rst.automodapi
- sphinx_automodapi/tests/cases/allowed_names/output/index.rst.automodsumm
- sphinx_automodapi/tests/example_module/noall.py
- sphinx_automodapi/tests/test_automodsumm.py
- sphinx_automodapi/tests/test_cases.py
- sphinx_automodapi/tests/test_utils.py
- sphinx_automodapi/utils.py
The present implementation of ``:allowed-package-names:`` was rather broken, as I found out when trying to use it on a module that is filled using entry points. This makes at least my case work.
cc @astrofrog - I note that there are quite a few PRs pending. Maybe good to try to get help in maintaining this??? (I may be able to do some).
> Fix allowed names

- sphinx_automodapi/automodsumm.py
I am trying to use automodapi with opsdroid, where we use `.md` files rather than `.rst` files as our narrative docs. This means that when we generate api docs with automodapi they get given a `.md` extension, which is just clearly wrong.
I don't really understand why we are generating ReST files with anything other than a `.rst` extension?!
> Always use .rst extension

- setup.cfg
- sphinx_automodapi/autodoc_enhancements.py
Removed PY2 compat and unused imports in `setup.cfg` and `autodoc_enhancements.py`.
> MNT: Code clean-up

- sphinx_automodapi/automodapi.py
- sphinx_automodapi/tests/test_automodapi.py
This is a potential solution for #92: This adds an `:include:` option to `automodapi`, if a user only wants to, e.g., pick a few object names to generate documentation for with `automodapi`. 
This is kind of a hack, because this implementation takes any object found that does not appear in `:include:` and adds them to the list of object names to skip before passing on to `automodsumm`. But hey, it seems to work 🤷‍♂️
> Add :include: option, to do the opposite of :skip:

- sphinx_automodapi/automodsumm.py
> Replace Autosummary.warn() calls with logger.warning() for Sphinx 4 compatibility

- sphinx_automodapi/smart_resolver.py
If intersphinx isn't used `env.intersphinx_named_inventory` fails in `smart_resolver.py`. This PR uses `getattr` to allow the default value of `{}`.
Closes #110
Closes #122
> Set default value for env.intersphinx_named_inventory

- CHANGES.rst
- setup.cfg
- sphinx_automodapi/automodapi.py
- sphinx_automodapi/tests/example_module/stdlib.py
- sphinx_automodapi/tests/test_automodapi.py
This is a fix for the bug identified in #141. The fix is implemented in the first commit from me, which simplifies some of the logic and reverts back to looking more like it did before #127 but keeps the new `:include:` functionality.
Note: this includes the commits from #140 which added a useful regression test.
cc @eslavich
EDIT:
* Fix #141 
* Close #140
> Fix issue with :skip: introduced by :include: feature

- tox.ini
Basically same as astropy/sphinx-astropy#55
> TST: Pin Jinja2 for older Sphinx

- CHANGES.rst
- docs/conf.py
- sphinx_automodapi/automodsumm.py
- sphinx_automodapi/tests/cases/non_ascii/input/index.rst
- sphinx_automodapi/tests/cases/non_ascii/output/api/sphinx_automodapi.tests.example_module.nonascii.NonAscii.rst
- sphinx_automodapi/tests/cases/non_ascii/output/index.rst.automodapi
- sphinx_automodapi/tests/cases/non_ascii/output/index.rst.automodsumm
- sphinx_automodapi/tests/example_module/nonascii.py
I just had an issue with non-ascii-characters in class members (in my case its a column name of a database I access with SQLAlchemy). This PR sets a default `encoding` for `open()` as the default seems to be os-dependent, howevers sphinx expects `utf8`. This fixes my issues on Windows.
I also tried to modify the non-ascii-testcase, however this seems to pass without my fix. If I execute normal `sphinx-build` during command-line it fails:
```shell
sphinx-build . _build
Sphinx v5.1.1 in Verwendung
making output directory... erledigt
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
[autosummary] generating autosummary for: index.rst
[automodsumm] index.rst: found 4 automodsumm entries to generate
building [mo]: targets for 0 po files that are out of date
building …
```
> Fix non ascii object members

- docs/conf.py
- setup.cfg
- sphinx_automodapi/automodapi.py
- sphinx_automodapi/automodsumm.py
- sphinx_automodapi/templates/autosummary_core/class.rst
- sphinx_automodapi/tests/duplicated_warning/docs/conf.py
- sphinx_automodapi/tests/duplicated_warning/docs/foo.rst
- sphinx_automodapi/tests/duplicated_warning/docs/index.rst
- sphinx_automodapi/tests/duplicated_warning/duplicated/__init__.py
- sphinx_automodapi/tests/duplicated_warning/duplicated/foo/__init__.py
- sphinx_automodapi/tests/duplicated_warning/duplicated/foo/foo.py
- sphinx_automodapi/tests/example_module/abstract_classes.py
- sphinx_automodapi/tests/test_cases.py
- sphinx_automodapi/utils.py
Fix #130.
TODO: see if I can add a test for this.
> Add option to set :noindex:

- .github/workflows/ci_workflows.yml
- setup.cfg
- sphinx_automodapi/tests/helpers.py
- tox.ini
While trying to make a release I found a few issues with recent version of tox and sphinx ...
> Updates for tox and sphinx

- sphinx_automodapi/utils.py
> Silence spurious warning on autosummary config

- .github/workflows/ci_workflows.yml
- .github/workflows/publish.yml
- CHANGES.rst
> Preparing v0.15.0 release

- .github/workflows/ci_workflows.yml
- setup.cfg
Remove the codecov PyPI package from the dependencies. The workflow is already using the codecov uploader action, so this should not be needed, unless coverage needs to uploaded from elsewhere?
> Remove PyPI codecov

- setup.cfg
This should fix all the CI failures we see on `main`: https://github.com/astropy/sphinx-automodapi/actions/runs/4748458397/jobs/8434673280
> MAINT: ignoring pip deprecation issued for old pythons

- .readthedocs.yml
- setup.cfg
Might be caused by https://github.com/readthedocs/sphinx_rtd_theme/issues/1463
> DOC: Fix RTD build

- setup.cfg
This deprecation warning has been reverted, so we shouldn't ignore the warning.
> Fix: remove ignore of reverted deprecation

- sphinx_automodapi/automodsumm.py
sphinx-doc/sphinx#10614 fixes many of the broken inheritance-diagram links (#48).  The remaining broken links are due to a bad interaction with `sphinx-automodapi`'s smart resolver.  
`sphinx.ext.inheritance_diagram` generates a list of class full names (e.g., `astropy.coordinates.baseframe.BaseCoordinateFrame`) and generates a mapping from class full names to documentation URLs.  However, the smart resolver causes the generated mapping to be instead from class documented name (e.g., `astropy.coordinates.BaseCoordinateFrame`) to documentation URLs.  The class documented name can be different from the class full name if the class is not documented where it is defined, but rather at some other location where it is imported.  In such situations, the code will fail to find the URL that for …
> Fix broken inheritance-diagram links due to the smart resolver

- .github/workflows/ci_workflows.yml
- .readthedocs.yml
- CHANGES.rst
- setup.cfg
- tox.ini
Close #173 by updating matrix. The compatibility was already addressed in #172 .
> TST: Update matrix

- .github/workflows/ci_workflows.yml
- CHANGES.rst
- setup.cfg
- tox.ini
MNT: Drop Python 3.7
TST: Test against Sphinx 7.2 instead of 7.1
Fix #175
> MNT: Drop Python 3.7 and update test matrix again

- .github/workflows/ci_workflows.yml
- .readthedocs.yml
Not sure how this ever passed in https://github.com/astropy/sphinx-automodapi/pull/177, but it's clearly causing issues in the cron tests.
> CI: fix environment name

- .github/workflows/ci_workflows.yml
- .github/workflows/publish.yml
- .readthedocs.yml
I noticed these out-of-dates versions while looking into reasons why we keep seeing failures in the OSX cron job. (They are unrelated to `sphinx-automodapi`, the job is always failing in the brew install parts, and sometimes passes after a restart or two.
> CI: update versions

- CHANGES.rst
- sphinx_automodapi/automodsumm.py
- sphinx_automodapi/tests/cases/slots/README.md
- sphinx_automodapi/tests/cases/slots/input/index.rst
- sphinx_automodapi/tests/cases/slots/output/api/sphinx_automodapi.tests.example_module.slots.DerivedParam.rst
- sphinx_automodapi/tests/cases/slots/output/api/sphinx_automodapi.tests.example_module.slots.DerivedSlotParam.rst
- sphinx_automodapi/tests/cases/slots/output/api/sphinx_automodapi.tests.example_module.slots.SlotDict.rst
- sphinx_automodapi/tests/cases/slots/output/index.rst.automodapi
- sphinx_automodapi/tests/cases/slots/output/index.rst.automodsumm
- sphinx_automodapi/tests/example_module/slots.py
- sphinx_automodapi/tests/test_cases.py
Fixes #168 and adds test case to prevent regression
> Updated "Use __dict__ and ignore __slots__ on classes #169

- sphinx_automodapi/automodapi.py
- sphinx_automodapi/automodsumm.py
This is the rebased version of #103 (as that one was opened from an org fork, maintainers cannot directly push to it)
EDIT: close #121
> Add automodsumm_included_members option, take2

- sphinx_automodapi/automodapi.py
- sphinx_automodapi/automodsumm.py
- sphinx_automodapi/tests/test_automodsumm.py
- sphinx_automodapi/utils.py
> Add sort option to automodsumm

- .github/workflows/ci_workflows.yml
- tox.ini
I don't expect any issues here, nevertheless, it's good to explicitly add the next major release to the testing matrix.
> MAINT: adding sphinx 8.0.x to the testing matrix

- CHANGES.rst
- sphinx_automodapi/tests/cases/public_from_private/README.md
- sphinx_automodapi/tests/cases/public_from_private/input/index.rst
- sphinx_automodapi/tests/cases/public_from_private/output/api/sphinx_automodapi.tests.example_module.public.Camelot.rst
- sphinx_automodapi/tests/cases/public_from_private/output/api/sphinx_automodapi.tests.example_module.public.Spam.rst
- sphinx_automodapi/tests/cases/public_from_private/output/index.rst.automodapi
- sphinx_automodapi/tests/cases/public_from_private/output/index.rst.automodsumm
- sphinx_automodapi/tests/example_module/_private.py
- sphinx_automodapi/tests/example_module/public.py
- sphinx_automodapi/utils.py
- tox.ini
Investigating the issue from https://github.com/astropy/astropy/pull/16974
> Added test case for importing a class from a private submodule into a public one

- .github/dependabot.yml
- .github/workflows/check_milestone.yml
- .github/workflows/ci_workflows.yml
- .github/workflows/publish.yml
As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)
> MNT: Use hash for Action workflow versions and update if needed

- setup.cfg
- sphinx_automodapi/automodsumm.py
Goal: Fix devdeps CI
I followed diff in https://github.com/sphinx-doc/sphinx/pull/13212
> Compatibility with Sphinx 8.2, minor clean up

- .github/workflows/ci_workflows.yml
- .github/workflows/publish.yml
- .readthedocs.yml
- LICENSE.rst
- MANIFEST.in
- pyproject.toml
- setup.cfg
- setup.py
- tox.ini
Unpin something that is outdated by now. Also I don't think this package has been alpha for a long time.
> DOC: Unpin outdated RTD sphinx maxversion

- .github/workflows/publish.yml
The release has run into this issue that some but not all of the test dependencies were manually listed, I rather switch to the config based approach.
> CI: install all test dependencies for test job

- sphinx_automodapi/autodoc_enhancements.py
- sphinx_automodapi/automodsumm.py
- sphinx_automodapi/tests/test_autodoc_enhancements.py
- Rebase https://github.com/astropy/sphinx-automodapi/pull/116 to fix #115
- Clean up exception handling and `if` statements as requested by @bsipocz (https://github.com/astropy/sphinx-automodapi/pull/116#discussion_r1166130661, https://github.com/astropy/sphinx-automodapi/pull/116#discussion_r1166131425).
- For fields that don't have a default value, report the default value as [`dataclasses.MISSING`](https://docs.python.org/3/library/dataclasses.html#dataclasses.MISSING) rather than incorrectly reporting the name of the field as the default value.
> Support for non-default dataclass fields (continuation of stale PR, https://github.com/astropy/sphinx-automodapi/pull/116)

- .github/workflows/ci_workflows.yml
- tox.ini
The sphinxdev jobs will fail, but we need to double check if there is anything new mixed in there due to python 3.14
> CI: adding Python 3.14 for testing
